import type { BoatConfiguration } from "@/lib/sim/boat-physics";

export type BoatVisualProfile = {
  /** Overall silhouette family for visuals. */
  hullProfile?: "trawler" | "express" | "flybridge" | "superyacht";
  aftDeckLengthRatio: number;
  aftDeckOffsetZRatio: number;
  deckhouseAftHalfWidthRatio: number;
  deckhouseBowHalfWidthRatio: number;
  deckhouseHeight: number;
  deckhouseLengthRatio: number;
  deckhouseOffsetZRatio: number;
  flybridgeHeight: number;
  flybridgeLengthRatio: number;
  flybridgeOffsetZRatio: number;
  flybridgeWidthRatio: number;
  hullColor: string;
  houseColor: string;
  mastHeight: number;
  mastOffsetZRatio: number;
  railColor: string;
  roofColor: string;
  superstructureStyle: "classic" | "expedition";
  swimPlatformLengthRatio: number;
  upperHelmHeight: number;
  upperHelmLengthRatio: number;
  upperHelmOffsetZRatio: number;
  upperHelmWidthRatio: number;
  windowColor: string;
};

// Helm appearance (bezels, instrument style, plotter palette) lives in
// helm-theme.ts, keyed by profileSlug — it describes what the helm is made of
// rather than a handful of loose colours, so it doesn't belong in the spec
// sheet.
export type BoatProfile = {
  charterUrl: string;
  description: string;
  displayName: string;
  highlights: string[];
  homePort?: string;
  manufacturer: string;
  model: string;
  profileSlug: string;
  simStatus: "ready" | "experimental";
  sources: Array<{
    label: string;
    url: string;
  }>;
  stats: {
    beam: string;
    cabins: number;
    cruiseSpeed: string;
    displacement: string;
    draft: string;
    engineNotes: string;
    fuel: string;
    holding: string;
    loa: string;
    maxSpeed: string;
    passengers?: string;
    sleeps: number;
    sternThruster?: string;
    thruster: string;
    stabilizers: string;
    water: string;
  };
  summary: string;
  visual: BoatVisualProfile;
  economics?: {
    /** Estimated replacement value (USD). Used for cost-of-damage estimates. */
    replacementValueUsd?: number;
    /** Rough cost-per-% hull damage. If omitted, a nonlinear model is used. */
    costPerPctDamageUsd?: number;
  };
} & BoatConfiguration;

export const DEFAULT_BOAT_SLUG = "52-grand-banks-bonum-vitae";

export const BOAT_CATALOG: BoatProfile[] = [
  {
    profileSlug: "52-grand-banks-bonum-vitae",
    displayName: "Bonum Vitae",
    manufacturer: "Grand Banks",
    model: "52 Heritage Motoryacht",
    charterUrl: "https://www.nwexplorations.com/charter-boats/52-grand-banks-2/",
    sources: [
      {
        label: "NW Explorations charter listing",
        url: "https://www.nwexplorations.com/charter-boats/52-grand-banks-2/",
      },
      {
        label: "Grand Banks / boats.com measured listing",
        url: "https://ca.boats.com/power-boats/2000-grand-banks-heritage-europa-52-8178843/",
      },
    ],
    summary:
      "Custom Grand Banks 52 motoryacht with cockpit, covered aft deck, flybridge, twin Caterpillar diesels, stabilizers, and bow thruster.",
    description:
      "Bonum Vitae is the simulator’s primary docking platform: a semi-displacement Grand Banks with a rare cockpit layout, strong low-speed maneuvering cues, and the classic covered-aft-deck / flybridge profile you’ll actually be handling.",
    highlights: [
      "Custom 52 MY built on the Grand Banks 49 platform with cockpit",
      "Twin Caterpillar 3126 diesels",
      "Bow thruster and stabilizers",
      "Covered aft deck, sundeck, and flybridge",
    ],
    homePort: "Bellingham, WA",
    simStatus: "ready",
    label: "Grand Banks 52 Heritage",
    massKg: 58_000 * 0.45359237,
    lengthM: 52 * 0.3048,
    beamM: (15 + 5 / 12) * 0.3048,
    engineLateralOffsetM: ((15 + 5 / 12) * 0.3048) * 0.34,
    // Close-quarters responsiveness: a touch more yaw authority and less surge
    // drag than the raw numbers suggest, to match how the real boat feels at
    // manoeuvring speed.
    forwardYawAuthorityScale: 0.98,
    reverseYawAuthorityScale: 0.8,
    engineLongitudinalOffsetM: -(52 * 0.3048) * 0.34,
    bowThrusterLongitudinalOffsetM: (52 * 0.3048) * 0.37,
    windCenterLongitudinalOffsetM: (52 * 0.3048) * 0.08,
    // Calibrated from the real boat's observed cruise point: roughly 12 kn
    // at 1,500–1,550 RPM, while retaining the published ~20 kn full-power
    // speed. The steeper curve keeps near-idle docking thrust essentially
    // unchanged instead of making the boat leap forward in close quarters.
    maxForwardThrustN: 54_800,
    maxReverseThrustN: 6_800,
    maxBowThrusterForceN: 2_600,
    maxPropWalkForceN: 680,
    throttleExponent: 2.704,
    throttleLinearBlend: 0.0285,
    waterLinearDragSurge: 720,
    waterLinearDragSway: 18_000,
    waterDragSurge: 250,
    waterDragSway: 12_000,
    yawLinearDrag: 120_000,
    yawDrag: 180_000,
    windageAreaM2: 34,
    windLongitudinalCoefficient: 0.55,
    windLateralCoefficient: 1.2,
    propellerHandedness: {
      port: "left",
      starboard: "right",
    },
    visual: {
      hullProfile: "trawler",
      aftDeckLengthRatio: 0.16,
      aftDeckOffsetZRatio: 0.29,
      deckhouseAftHalfWidthRatio: 0.22,
      deckhouseBowHalfWidthRatio: 0.155,
      deckhouseHeight: 0.92,
      deckhouseLengthRatio: 0.16,
      deckhouseOffsetZRatio: -0.165,
      flybridgeHeight: 0.36,
      flybridgeLengthRatio: 0.18,
      flybridgeOffsetZRatio: 0.29,
      flybridgeWidthRatio: 0.4,
      hullColor: "#efe7d3",
      houseColor: "#d5c6a7",
      mastHeight: 0.92,
      mastOffsetZRatio: -0.04,
      railColor: "#d7b97d",
      roofColor: "#f7f4eb",
      superstructureStyle: "classic",
      swimPlatformLengthRatio: 0.09,
      upperHelmHeight: 0.3,
      upperHelmLengthRatio: 0.08,
      upperHelmOffsetZRatio: -0.135,
      upperHelmWidthRatio: 0.18,
      windowColor: "#89a9bf",
    },
    stats: {
      beam: "15' 5\"",
      cabins: 3,
      cruiseSpeed: "15 kn",
      displacement: "58,000 lb",
      draft: "5' 2\"",
      engineNotes: "Twin Caterpillar 3126, 420 hp each",
      fuel: "1,200 gal",
      holding: "50 gal",
      loa: "52'",
      maxSpeed: "20 kn",
      sleeps: 4,
      sternThruster: "No",
      thruster: "Bow thruster",
      stabilizers: "Yes",
      water: "500 gal",
    },
    economics: { replacementValueUsd: 1_000_000 },
  },
  {
    profileSlug: "86-nordhavn-serendipity",
    displayName: "Serendipity",
    manufacturer: "Nordhavn",
    model: "N86",
    charterUrl: "https://www.nwexplorations.com/charter-boats/serendipity-86-nordhavn/",
    sources: [
      {
        label: "NW Explorations charter listing",
        url: "https://www.nwexplorations.com/charter-boats/serendipity-86-nordhavn/",
      },
      {
        label: "Nordhavn N86 official specs",
        url: "https://nordhavn.com/nordhavn-yacht-models/n86/",
      },
    ],
    summary:
      "Crewed Nordhavn 86 expedition yacht with twin C18 diesels, 4,000 nm range, huge beam, and megayacht-scale systems.",
    description:
      "Serendipity is not a casual bareboat. It is a big, heavy, ocean-capable expedition platform whose official N86 spec sheet gives us a solid baseline for a second simulated profile and a useful contrast against Bonum Vitae.",
    highlights: [
      "Official N86 dimensions and displacement from Nordhavn",
      "Twin 600 hp Caterpillar C18s per Nordhavn N86 spec",
      "4,000 nm range at 9-10 kn",
      "Crewed charter only on NW Explorations",
    ],
    homePort: "Bellingham, WA",
    simStatus: "experimental",
    label: "Nordhavn 86",
    massKg: 400_000 * 0.45359237,
    lengthM: (86 + 7 / 12) * 0.3048,
    beamM: 24 * 0.3048,
    engineLateralOffsetM: (24 * 0.3048) * 0.29,
    forwardYawAuthorityScale: 0.9,
    reverseYawAuthorityScale: 0.74,
    engineLongitudinalOffsetM: -((86 + 7 / 12) * 0.3048) * 0.35,
    bowThrusterLongitudinalOffsetM: ((86 + 7 / 12) * 0.3048) * 0.4,
    windCenterLongitudinalOffsetM: ((86 + 7 / 12) * 0.3048) * 0.09,
    maxForwardThrustN: 16_000,
    maxReverseThrustN: 12_800,
    maxBowThrusterForceN: 8_000,
    maxPropWalkForceN: 1_500,
    throttleExponent: 1.85,
    throttleLinearBlend: 0.14,
    waterLinearDragSurge: 1_600,
    waterLinearDragSway: 55_000,
    waterDragSurge: 250,
    waterDragSway: 28_000,
    yawLinearDrag: 360_000,
    yawDrag: 560_000,
    windageAreaM2: 82,
    windLongitudinalCoefficient: 0.68,
    windLateralCoefficient: 1.46,
    propellerHandedness: {
      port: "left",
      starboard: "right",
    },
    visual: {
      hullProfile: "superyacht",
      aftDeckLengthRatio: 0.12,
      aftDeckOffsetZRatio: 0.22,
      deckhouseAftHalfWidthRatio: 0.34,
      deckhouseBowHalfWidthRatio: 0.26,
      deckhouseHeight: 1.24,
      deckhouseLengthRatio: 0.26,
      deckhouseOffsetZRatio: -0.08,
      flybridgeHeight: 0.44,
      flybridgeLengthRatio: 0.14,
      flybridgeOffsetZRatio: 0.05,
      flybridgeWidthRatio: 0.42,
      hullColor: "#e6e0d0",
      houseColor: "#d5cfbf",
      mastHeight: 1.3,
      mastOffsetZRatio: -0.01,
      railColor: "#cba968",
      roofColor: "#f5f1e7",
      superstructureStyle: "expedition",
      swimPlatformLengthRatio: 0.05,
      upperHelmHeight: 0.42,
      upperHelmLengthRatio: 0.09,
      upperHelmOffsetZRatio: -0.03,
      upperHelmWidthRatio: 0.22,
      windowColor: "#7b9ab0",
    },
    stats: {
      beam: "24' 0\"",
      cabins: 3,
      cruiseSpeed: "10 kn",
      displacement: "400,000 lb",
      draft: "6' 11\"",
      engineNotes: "Twin Caterpillar C18, 600 hp each",
      fuel: "7,000 gal",
      holding: "250 gal black / 210 gal grey",
      loa: "87' 7\"",
      maxSpeed: "12 kn",
      sleeps: 6,
      sternThruster: "Yes",
      thruster: "Bow and stern thrusters",
      stabilizers: "Yes",
      water: "900 gal",
    },
    economics: { replacementValueUsd: 7_500_000 },
  },
  {
    profileSlug: "55-nordhavn-penalty-box-iii",
    displayName: "Penalty Box III",
    manufacturer: "Nordhavn",
    model: "55",
    charterUrl: "https://www.nwexplorations.com/charter-boats/55-nordhavn-2/",
    sources: [
      { label: "NW Explorations charter page", url: "https://www.nwexplorations.com/charter-boats/55-nordhavn-2/" },
      { label: "Nordhavn 55 brochure/summary (JMYS)", url: "https://nordhavn55.com/specifications/" },
    ],
    summary: "Expedition trawler with full displacement hull, single-screw main plus wing engine, and ocean crossing range.",
    description:
      "A long‑range, full‑displacement passagemaker with walk‑around engine room. We model close‑quarters handling conservatively to reflect the single‑screw pedigree while keeping twin‑lever control for simulator consistency.",
    highlights: [
      "Full‑displacement trawler hull",
      "Single main + wing engine on most hulls",
      "Massive fuel capacity for range",
    ],
    homePort: "Bellingham, WA",
    simStatus: "experimental",
    label: "Nordhavn 55",
    // Specs: LOA 56'1", Beam 18'0", Draft ~6'6", Disp ~124,500 lb (sources in page)
    massKg: 124_500 * 0.45359237,
    lengthM: 17.09,
    beamM: 5.49,
    engineLateralOffsetM: 5.49 * 0.32,
    forwardYawAuthorityScale: 0.82,
    reverseYawAuthorityScale: 0.70,
    engineLongitudinalOffsetM: -(17.09 * 0.36),
    bowThrusterLongitudinalOffsetM: 17.09 * 0.43,
    windCenterLongitudinalOffsetM: 17.09 * 0.12,
    maxForwardThrustN: 9_800,
    maxReverseThrustN: 7_600,
    maxBowThrusterForceN: 3_800,
    maxPropWalkForceN: 820,
    throttleExponent: 1.85,
    throttleLinearBlend: 0.16,
    waterLinearDragSurge: 1_050,
    waterLinearDragSway: 36_000,
    waterDragSurge: 360,
    waterDragSway: 18_000,
    yawLinearDrag: 220_000,
    yawDrag: 360_000,
    windageAreaM2: 48,
    windLongitudinalCoefficient: 0.60,
    windLateralCoefficient: 1.35,
    propellerHandedness: { port: "left", starboard: "right" },
    visual: {
      hullProfile: "trawler",
      aftDeckLengthRatio: 0.14,
      aftDeckOffsetZRatio: 0.26,
      deckhouseAftHalfWidthRatio: 0.26,
      deckhouseBowHalfWidthRatio: 0.19,
      deckhouseHeight: 1.05,
      deckhouseLengthRatio: 0.22,
      deckhouseOffsetZRatio: -0.08,
      flybridgeHeight: 0.40,
      flybridgeLengthRatio: 0.15,
      flybridgeOffsetZRatio: 0.22,
      flybridgeWidthRatio: 0.42,
      hullColor: "#e8e3d4",
      houseColor: "#d7d0be",
      mastHeight: 1.10,
      mastOffsetZRatio: -0.02,
      railColor: "#c7b083",
      roofColor: "#f3efe6",
      superstructureStyle: "expedition",
      swimPlatformLengthRatio: 0.05,
      upperHelmHeight: 0.41,
      upperHelmLengthRatio: 0.09,
      upperHelmOffsetZRatio: -0.01,
      upperHelmWidthRatio: 0.22,
      windowColor: "#7da0b3",
    },
    stats: {
      beam: "18' 0\"",
      cabins: 3,
      cruiseSpeed: "9–10 kn",
      displacement: "124,500 lb",
      draft: "6' 6\"",
      engineNotes: "Typically single main + wing; simulated with twin levers",
      fuel: "2,250 gal",
      holding: "—",
      loa: "56' 1\"",
      maxSpeed: "11–12 kn",
      sleeps: 6,
      sternThruster: "No",
      thruster: "Bow thruster",
      stabilizers: "Yes",
      water: "—",
    },
    economics: { replacementValueUsd: 2_200_000 },
  },
  {
    profileSlug: "2026-cranchi-e26-rider",
    displayName: "E26 Rider",
    manufacturer: "Cranchi",
    model: "E26 Rider (O/B)",
    charterUrl: "https://www.cranchi.com/yacht/e26-o-b/",
    sources: [
      { label: "Cranchi E26 O/B page", url: "https://www.cranchi.com/yacht/e26-o-b/" },
      { label: "Cranchi E26 technical data (PDF)", url: "https://www.cranchi.com/sites/default/files/pressRelease/cranchi-e26.pdf" },
    ],
    summary: "Sporty 26‑footer bowrider with outboard power; nimble and light.",
    description:
      "We approximate twin‑lever control by mapping the single outboard’s response symmetrically; bow thruster is disabled. Great for quick marina practice and handling fundamentals.",
    highlights: ["Outboard power", "Dry weight ~2.2 t", "Trailerable beam 2.49 m"],
    simStatus: "experimental",
    label: "Cranchi E26 Rider",
    massKg: 2_170,
    lengthM: 7.85,
    beamM: 2.49,
    engineLateralOffsetM: 2.49 * 0.25,
    forwardYawAuthorityScale: 1.18,
    reverseYawAuthorityScale: 0.82,
    engineLongitudinalOffsetM: -(7.85 * 0.28),
    bowThrusterLongitudinalOffsetM: 7.85 * 0.40,
    windCenterLongitudinalOffsetM: 7.85 * 0.10,
    maxForwardThrustN: 3_600,
    maxReverseThrustN: 2_600,
    maxBowThrusterForceN: 0,
    maxPropWalkForceN: 160,
    throttleExponent: 1.55,
    throttleLinearBlend: 0.22,
    waterLinearDragSurge: 180,
    waterLinearDragSway: 2_800,
    waterDragSurge: 90,
    waterDragSway: 1_600,
    yawLinearDrag: 9_800,
    yawDrag: 16_000,
    windageAreaM2: 6.2,
    windLongitudinalCoefficient: 0.50,
    windLateralCoefficient: 1.08,
    propellerHandedness: { port: "left", starboard: "right" },
    visual: {
      hullProfile: "express",
      aftDeckLengthRatio: 0.08,
      aftDeckOffsetZRatio: 0.12,
      deckhouseAftHalfWidthRatio: 0.18,
      deckhouseBowHalfWidthRatio: 0.16,
      deckhouseHeight: 0.46,
      deckhouseLengthRatio: 0.10,
      deckhouseOffsetZRatio: 0.02,
      flybridgeHeight: 0,
      flybridgeLengthRatio: 0,
      flybridgeOffsetZRatio: 0,
      flybridgeWidthRatio: 0,
      hullColor: "#0c1216",
      houseColor: "#d9d9d9",
      mastHeight: 0.0,
      mastOffsetZRatio: 0,
      railColor: "#bdbdbd",
      roofColor: "#e9e9e9",
      superstructureStyle: "expedition",
      swimPlatformLengthRatio: 0.04,
      upperHelmHeight: 0.0,
      upperHelmLengthRatio: 0.0,
      upperHelmOffsetZRatio: 0.0,
      upperHelmWidthRatio: 0.0,
      windowColor: "#7ea1b2",
    },
    stats: {
      beam: "8' 2\"",
      cabins: 0,
      cruiseSpeed: "24–28 kn",
      displacement: "2,170 kg (dry)",
      draft: "0.90 m",
      engineNotes: "Outboard 300–350 hp (approx.)",
      fuel: "270 L",
      holding: "—",
      loa: "7.85 m",
      maxSpeed: "40+ kn (engine dependent)",
      sleeps: 0,
      sternThruster: "No",
      thruster: "None",
      stabilizers: "No",
      water: "70 L",
    },
    economics: { replacementValueUsd: 190_000 },
  },
  {
    profileSlug: "2026-cranchi-settantotto-78",
    displayName: "Settantotto 78",
    manufacturer: "Cranchi",
    model: "Settantotto 78",
    charterUrl: "https://www.cranchi.com/it/yacht/settantotto-78/",
    sources: [
      { label: "Cranchi Settantotto 78 official", url: "https://www.cranchi.com/it/yacht/settantotto-78/" },
      { label: "Cranchi 78 IPS 1350 tech (PDF)", url: "https://www.cranchi.com/en/system/files/priceList/settantotto_78_ips_3xd13_1350_3x1000_hp_r1.pdf" },
      { label: "Dealer specs (beam/displacement)", url: "https://www.sundanceyachts.com/boats-for-sale/cranchi-yachts-settantotto-78" },
    ],
    summary: "Modern 82’6” flybridge with triple Volvo IPS 1350 and luxurious interior.",
    description:
      "We approximate triple IPS maneuverability with higher thrust and yaw authority while preserving believable docking behavior in tight quarters.",
    highlights: ["Triple Volvo D13‑IPS1350 (3×1000 hp)", "Beam ~5.76 m", "Displacement ~57 t light"],
    simStatus: "experimental",
    label: "Cranchi 78",
    massKg: 57_000,
    lengthM: 25.15,
    beamM: 5.76,
    engineLateralOffsetM: 5.76 * 0.30,
    forwardYawAuthorityScale: 1.02,
    reverseYawAuthorityScale: 0.86,
    engineLongitudinalOffsetM: -(25.15 * 0.33),
    bowThrusterLongitudinalOffsetM: 25.15 * 0.42,
    windCenterLongitudinalOffsetM: 25.15 * 0.11,
    maxForwardThrustN: 18_500,
    maxReverseThrustN: 14_200,
    maxBowThrusterForceN: 6_400,
    maxPropWalkForceN: 1_200,
    throttleExponent: 1.78,
    throttleLinearBlend: 0.16,
    waterLinearDragSurge: 1_350,
    waterLinearDragSway: 48_000,
    waterDragSurge: 420,
    waterDragSway: 24_000,
    yawLinearDrag: 440_000,
    yawDrag: 680_000,
    windageAreaM2: 92,
    windLongitudinalCoefficient: 0.62,
    windLateralCoefficient: 1.40,
    propellerHandedness: { port: "left", starboard: "right" },
    visual: {
      hullProfile: "flybridge",
      aftDeckLengthRatio: 0.12,
      aftDeckOffsetZRatio: 0.18,
      deckhouseAftHalfWidthRatio: 0.34,
      deckhouseBowHalfWidthRatio: 0.26,
      deckhouseHeight: 1.18,
      deckhouseLengthRatio: 0.24,
      deckhouseOffsetZRatio: -0.06,
      flybridgeHeight: 0.48,
      flybridgeLengthRatio: 0.18,
      flybridgeOffsetZRatio: 0.06,
      flybridgeWidthRatio: 0.44,
      hullColor: "#ece6d8",
      houseColor: "#dad4c5",
      mastHeight: 1.24,
      mastOffsetZRatio: -0.01,
      railColor: "#caa269",
      roofColor: "#f7f0e6",
      superstructureStyle: "expedition",
      swimPlatformLengthRatio: 0.06,
      upperHelmHeight: 0.44,
      upperHelmLengthRatio: 0.12,
      upperHelmOffsetZRatio: -0.02,
      upperHelmWidthRatio: 0.22,
      windowColor: "#88a7bd",
    },
    stats: {
      beam: "18' 10\"",
      cabins: 4,
      cruiseSpeed: "24–28 kn",
      displacement: "57,000 kg (light)",
      draft: "~1.9 m",
      engineNotes: "3× Volvo Penta D13‑IPS1350 (3×1000 hp)",
      fuel: "~5,900 L (typical fitout)",
      holding: "—",
      loa: "82' 6\" (25.15 m)",
      maxSpeed: "30+ kn",
      sleeps: 8,
      sternThruster: "Yes",
      thruster: "Bow & stern (typical)",
      stabilizers: "Yes",
      water: "~1,200 L",
    },
    economics: { replacementValueUsd: 6_000_000 },
  },
  {
    profileSlug: "2005-chris-craft-corsair-36",
    displayName: "Corsair 36",
    manufacturer: "Chris‑Craft",
    model: "Corsair 36",
    charterUrl: "https://pdf.nauticexpo.com/pdf/chris-craft/corsair-36/20133-47981.html",
    sources: [
      { label: "Chris‑Craft Corsair 36 brochure", url: "https://pdf.nauticexpo.com/pdf/chris-craft/corsair-36/20133-47981.html" },
    ],
    summary: "Classic mahogany‑inspired express cruiser with twin stern drives.",
    description:
      "A beautiful 36‑footer with tumblehome and a quick, responsive helm. We tune docking physics for confident low‑speed handling.",
    highlights: ["Twin gas stern drives", "Dry weight ~16,000 lb", "Beam 12'6\""],
    simStatus: "experimental",
    label: "Corsair 36",
    massKg: 16_000 * 0.45359237,
    lengthM: 11.63, // 38'2" overall incl. platform ~11.63 m
    beamM: 3.81,
    engineLateralOffsetM: 3.81 * 0.30,
    forwardYawAuthorityScale: 1.10,
    reverseYawAuthorityScale: 0.86,
    engineLongitudinalOffsetM: -(11.63 * 0.30),
    bowThrusterLongitudinalOffsetM: 11.63 * 0.40,
    windCenterLongitudinalOffsetM: 11.63 * 0.10,
    maxForwardThrustN: 6_200,
    maxReverseThrustN: 4_800,
    maxBowThrusterForceN: 0,
    maxPropWalkForceN: 380,
    throttleExponent: 1.60,
    throttleLinearBlend: 0.20,
    waterLinearDragSurge: 380,
    waterLinearDragSway: 6_800,
    waterDragSurge: 150,
    waterDragSway: 3_600,
    yawLinearDrag: 22_000,
    yawDrag: 36_000,
    windageAreaM2: 12,
    windLongitudinalCoefficient: 0.52,
    windLateralCoefficient: 1.10,
    propellerHandedness: { port: "left", starboard: "right" },
    visual: {
      hullProfile: "express",
      aftDeckLengthRatio: 0.10,
      aftDeckOffsetZRatio: 0.16,
      deckhouseAftHalfWidthRatio: 0.26,
      deckhouseBowHalfWidthRatio: 0.20,
      deckhouseHeight: 0.62,
      deckhouseLengthRatio: 0.16,
      deckhouseOffsetZRatio: -0.02,
      flybridgeHeight: 0,
      flybridgeLengthRatio: 0,
      flybridgeOffsetZRatio: 0,
      flybridgeWidthRatio: 0,
      hullColor: "#1c2328",
      houseColor: "#d7d4c8",
      mastHeight: 0,
      mastOffsetZRatio: 0,
      railColor: "#b9b09e",
      roofColor: "#ebe6db",
      superstructureStyle: "classic",
      swimPlatformLengthRatio: 0.06,
      upperHelmHeight: 0.0,
      upperHelmLengthRatio: 0.0,
      upperHelmOffsetZRatio: 0.0,
      upperHelmWidthRatio: 0.0,
      windowColor: "#87a4b7",
    },
    stats: {
      beam: "12' 6\"",
      cabins: 1,
      cruiseSpeed: "26–30 kn",
      displacement: "16,000 lb (dry)",
      draft: "3' 2\" (drives down)",
      engineNotes: "Twin gas stern drives (typical build)",
      fuel: "~946 L (250 gal) typical",
      holding: "—",
      loa: "38' 2\" overall",
      maxSpeed: "48–51 mph (brochure)",
      sleeps: 2,
      sternThruster: "No",
      thruster: "None",
      stabilizers: "No",
      water: "~132 L (35 gal)",
    },
    economics: { replacementValueUsd: 200_000 },
  },
  {
    profileSlug: "1997-crescent-custom-114",
    displayName: "Crescent 114",
    manufacturer: "Crescent Custom Yachts",
    model: "114 Raised Pilothouse",
    charterUrl: "https://www.boats.com/power-boats/1997-crescent-custom-114-10293220/",
    sources: [
      { label: "Boats.com listing (beam/draft/engines)", url: "https://www.boats.com/power-boats/1997-crescent-custom-114-10293220/" },
      { label: "Comparable Crescent 115 displacement (YATCO)", url: "https://www.yatco.com/yachts/kapalua-crescent-1996-83732/" },
    ],
    summary: "Classic 114’ semi‑displacement GRP yacht with twin Detroit 16V92TA.",
    description:
      "Large, stable platform for advanced docking practice. Parameters scaled for semi‑displacement handling; powerful thrusters and windage modeled.",
    highlights: ["Twin Detroit Diesel 16V92TA (~2,900 hp combined)", "Beam ~24.7 ft", "Draft ~6 ft"],
    simStatus: "experimental",
    label: "Crescent 114",
    massKg: 274_300 * 0.45359237, // approximate, from comparable 115
    lengthM: 34.75,
    beamM: 7.31,
    engineLateralOffsetM: 7.31 * 0.32,
    forwardYawAuthorityScale: 0.96,
    reverseYawAuthorityScale: 0.82,
    engineLongitudinalOffsetM: -(34.75 * 0.34),
    bowThrusterLongitudinalOffsetM: 34.75 * 0.44,
    windCenterLongitudinalOffsetM: 34.75 * 0.12,
    maxForwardThrustN: 28_000,
    maxReverseThrustN: 22_000,
    maxBowThrusterForceN: 9_000,
    maxPropWalkForceN: 1_800,
    throttleExponent: 1.85,
    throttleLinearBlend: 0.14,
    waterLinearDragSurge: 2_800,
    waterLinearDragSway: 120_000,
    waterDragSurge: 680,
    waterDragSway: 60_000,
    yawLinearDrag: 1_100_000,
    yawDrag: 1_800_000,
    windageAreaM2: 210,
    windLongitudinalCoefficient: 0.66,
    windLateralCoefficient: 1.52,
    propellerHandedness: { port: "left", starboard: "right" },
    visual: {
      hullProfile: "superyacht",
      aftDeckLengthRatio: 0.14,
      aftDeckOffsetZRatio: 0.20,
      deckhouseAftHalfWidthRatio: 0.38,
      deckhouseBowHalfWidthRatio: 0.30,
      deckhouseHeight: 1.40,
      deckhouseLengthRatio: 0.28,
      deckhouseOffsetZRatio: -0.04,
      flybridgeHeight: 0.50,
      flybridgeLengthRatio: 0.16,
      flybridgeOffsetZRatio: 0.06,
      flybridgeWidthRatio: 0.44,
      hullColor: "#f3f3f3",
      houseColor: "#e9e9e7",
      mastHeight: 1.32,
      mastOffsetZRatio: -0.01,
      railColor: "#d1c7b3",
      roofColor: "#fafafa",
      superstructureStyle: "expedition",
      swimPlatformLengthRatio: 0.07,
      upperHelmHeight: 0.44,
      upperHelmLengthRatio: 0.11,
      upperHelmOffsetZRatio: -0.02,
      upperHelmWidthRatio: 0.22,
      windowColor: "#a1b8c7",
    },
    stats: {
      beam: "24.7' (approx.)",
      cabins: 5,
      cruiseSpeed: "18–20 kn",
      displacement: "≈274,300 lb (comparable 115')",
      draft: "6' (approx.)",
      engineNotes: "Twin Detroit Diesel 16V92TA",
      fuel: "—",
      holding: "—",
      loa: "114'",
      maxSpeed: "~21 kn",
      sleeps: 8,
      sternThruster: "Yes",
      thruster: "Bow & stern",
      stabilizers: "Yes",
      water: "—",
    },
    economics: { replacementValueUsd: 5_000_000 },
  },
];

export function getBoatProfile(slug: string | null | undefined) {
  if (!slug) {
    return BOAT_CATALOG[0];
  }

  return BOAT_CATALOG.find((boat) => boat.profileSlug === slug) ?? BOAT_CATALOG[0];
}
